blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://github.com/staras-godeltech/AI-Adoption-GitHub-Copilot/docs
    about: Please check documentation before creating issues
